/**
 * useContract Hook
 *
 * Real-time subscription to the contract document for a deal.
 * Follows the useDeal.js pattern exactly.
 *
 * The contract is stored at: deals/{dealId}/contract/main
 * It is auto-generated by the onDealAccepted Cloud Function.
 *
 * Usage:
 * const { contract, loading, error } = useContract(dealId);
 */

'use client';

import { useState, useEffect } from 'react';
import { container } from '@/core/di/container';

/**
 * Subscribe to the contract document for a deal in real time.
 *
 * @param {string|null} dealId - Firestore deal document ID
 * @returns {{ contract: import('@/domain/entities/Contract').Contract|null, loading: boolean, error: string|null }}
 */
export function useContract(dealId) {
  const [contract, setContract] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    if (!dealId) {
      setLoading(false);
      return;
    }

    setLoading(true);
    setError(null);

    const contractRepo = container.getContractRepository();

    const unsub = contractRepo.subscribeToContract(dealId, (contractData) => {
      setContract(contractData);
      setLoading(false);
    });

    return () => unsub();
  }, [dealId]);

  return { contract, loading, error };
}

export default useContract;
