/**
 * Contract Entity
 *
 * Represents the dual-party contract approval document for an accepted deal.
 * Stored at: deals/{dealId}/contract/main
 *
 * The contract is auto-generated by the onDealAccepted Cloud Function when a deal
 * transitions to 'accepted' status. Both parties must independently approve all
 * clauses before the deal advances to 'contract_approved'.
 *
 * Follows the same pattern as Deal.js and Offer.js entities.
 */

import { CONTRACT_STATUS } from '@/core/constants/contractConstants';

export class Contract {
  /**
   * Constructor
   * @param {string} id - Document ID (always 'main' for the contract subcollection)
   * @param {string} dealId - Parent deal ID (denormalized)
   * @param {string} dealBuyerId - Buyer UID (denormalized from deal for buyer/seller lookup)
   * @param {string} dealSellerId - Seller UID (denormalized from deal for buyer/seller lookup)
   * @param {Date|null} generatedAt - When the contract was auto-generated
   * @param {Date|null} deadline - Optional contract approval deadline (null = no enforcement)
   * @param {Object[]} clauses - Array of contract clause objects
   * @param {Object} buyerApproval - Buyer approval state { approvedClauses, hasSubmitted, submittedAt }
   * @param {Object} sellerApproval - Seller approval state { approvedClauses, hasSubmitted, submittedAt }
   * @param {string} status - CONTRACT_STATUS enum value
   */
  constructor({
    id,
    dealId,
    dealBuyerId,
    dealSellerId,
    generatedAt,
    deadline,
    clauses,
    buyerApproval,
    sellerApproval,
    status,
  }) {
    this.id = id;
    this.dealId = dealId;
    this.dealBuyerId = dealBuyerId;
    this.dealSellerId = dealSellerId;
    this.generatedAt = generatedAt || null;
    this.deadline = deadline || null;
    this.clauses = clauses || [];
    this.buyerApproval = buyerApproval || {
      approvedClauses: [],
      hasSubmitted: false,
      submittedAt: null,
    };
    this.sellerApproval = sellerApproval || {
      approvedClauses: [],
      hasSubmitted: false,
      submittedAt: null,
    };
    this.status = status || CONTRACT_STATUS.PENDING;
  }

  /**
   * Create Contract from Firestore document snapshot.
   * Converts Firestore Timestamps to JS Dates.
   * @param {import('firebase/firestore').DocumentSnapshot} snap - Firestore snapshot
   * @returns {Contract}
   */
  static fromFirestore(snap) {
    const data = snap.data();
    const id = snap.id;

    const buyerApproval = {
      approvedClauses: data.buyerApproval?.approvedClauses || [],
      hasSubmitted: data.buyerApproval?.hasSubmitted || false,
      submittedAt: data.buyerApproval?.submittedAt?.toDate?.() || data.buyerApproval?.submittedAt || null,
    };

    const sellerApproval = {
      approvedClauses: data.sellerApproval?.approvedClauses || [],
      hasSubmitted: data.sellerApproval?.hasSubmitted || false,
      submittedAt: data.sellerApproval?.submittedAt?.toDate?.() || data.sellerApproval?.submittedAt || null,
    };

    return new Contract({
      id,
      dealId: data.dealId,
      dealBuyerId: data.dealBuyerId,
      dealSellerId: data.dealSellerId,
      generatedAt: data.generatedAt?.toDate?.() || data.generatedAt || null,
      deadline: data.deadline?.toDate?.() || data.deadline || null,
      clauses: data.clauses || [],
      buyerApproval,
      sellerApproval,
      status: data.status || CONTRACT_STATUS.PENDING,
    });
  }

  // ─────────────────────────────────────────────────────────────────────────
  // Participation helpers
  // ─────────────────────────────────────────────────────────────────────────

  /**
   * Check if the given UID is the buyer in this contract.
   * Uses denormalized dealBuyerId — no extra Firestore read required.
   * @param {string} uid
   * @returns {boolean}
   */
  isBuyer(uid) {
    return uid === this.dealBuyerId;
  }

  // ─────────────────────────────────────────────────────────────────────────
  // Approval state helpers
  // ─────────────────────────────────────────────────────────────────────────

  /**
   * Get the approval state for the current user.
   * @param {string} uid - Current user's UID
   * @param {Object} deal - Deal entity or plain deal object (kept for API compatibility)
   * @returns {{ approvedClauses: string[], hasSubmitted: boolean, submittedAt: Date|null }}
   */
  getMyApproval(uid, deal) {
    return this.isBuyer(uid) ? this.buyerApproval : this.sellerApproval;
  }

  /**
   * Get the approval state for the other party.
   * @param {string} uid - Current user's UID
   * @param {Object} deal - Deal entity or plain deal object (kept for API compatibility)
   * @returns {{ approvedClauses: string[], hasSubmitted: boolean, submittedAt: Date|null }}
   */
  getOtherApproval(uid, deal) {
    return this.isBuyer(uid) ? this.sellerApproval : this.buyerApproval;
  }

  // ─────────────────────────────────────────────────────────────────────────
  // Clause grouping
  // ─────────────────────────────────────────────────────────────────────────

  /**
   * Group clauses by their section ID.
   * @returns {Object} Object mapping section ID -> clause[]
   */
  getClausesBySection() {
    return this.clauses.reduce((acc, clause) => {
      const sectionId = clause.section;
      if (!acc[sectionId]) acc[sectionId] = [];
      acc[sectionId].push(clause);
      return acc;
    }, {});
  }

  // ─────────────────────────────────────────────────────────────────────────
  // Status helpers
  // ─────────────────────────────────────────────────────────────────────────

  /**
   * Check if both parties have submitted their approvals.
   * @returns {boolean}
   */
  isFullyApproved() {
    return this.status === CONTRACT_STATUS.BOTH_APPROVED;
  }

  // ─────────────────────────────────────────────────────────────────────────
  // Progress helpers
  // ─────────────────────────────────────────────────────────────────────────

  /**
   * Get the approval progress for the current user.
   * @param {string} uid - Current user's UID
   * @param {Object} deal - Deal entity or plain deal object (kept for API compatibility)
   * @returns {{ approved: number, total: number }}
   */
  getMyProgress(uid, deal) {
    const myApproval = this.getMyApproval(uid, deal);
    return {
      approved: myApproval.approvedClauses.length,
      total: this.clauses.length,
    };
  }

  /**
   * Get the approval progress for the other party.
   * @param {string} uid - Current user's UID
   * @param {Object} deal - Deal entity or plain deal object (kept for API compatibility)
   * @returns {{ approved: number, total: number }}
   */
  getOtherProgress(uid, deal) {
    const otherApproval = this.getOtherApproval(uid, deal);
    return {
      approved: otherApproval.approvedClauses.length,
      total: this.clauses.length,
    };
  }
}

export default Contract;
